#!/usr/bin/env php
<?php
/**
 * ???????
 *
 * @author    XueronNi <xueronni@uniondrug.cn>
 * @copyright 2018
 */
set_time_limit(0);
date_default_timezone_set('PRC');

// autoload composer
foreach ([
             getcwd() . '/vendor/autoload.php',
             __DIR__ . '/../../autoload.php',
             __DIR__ . '/../vendor/autoload.php',
             __DIR__ . '/vendor/autoload.php',
         ] as $value) {
    if (file_exists($value)) {
        define('COMPOSER_INSTALL', $value);
        break;
    }
}

if (!defined('COMPOSER_INSTALL')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
}

include COMPOSER_INSTALL;

use Pails\Application;
use Pails\Container;
use UniondrugConsole\Console;

/**
 * This code
 *
 * __DIR__ . '/app'
 *
 * is test code.
 */
$path = file_exists('.') ? '.' : getcwd();
try {
    // Process --env -e
    __parseEnv();

    $container = new Container($path);
    $application = (new Application($container))->boot();
    $console = new Console($container);

    $console->run();
} catch (Throwable $e) {
    echo PHP_EOL;
    echo "Error: " . $e->getMessage() . PHP_EOL;
    //echo PHP_EOL;
    echo " File: " . $e->getFile() . PHP_EOL;
    echo " Line: " . $e->getLine() . PHP_EOL;
    echo PHP_EOL;
    echo "Trace:" . PHP_EOL;
    echo $e->getTraceAsString();
    echo PHP_EOL;
}

function __parseEnv()
{
    $env = 'development';
    $args = $_SERVER['argv'];
    array_shift($args);
    while ($token = array_shift($args)) {
        if ($token == '-e') {
            if ($inputEnv = array_shift($args)) {
                $env = $inputEnv;
                break;
            }
        }
        if (0 === strpos($token, '--env')) {
            if (false !== $pos = strpos($token, '=')) {
                $inputEnv = substr($token, $pos + 1);
                if ($inputEnv) {
                    $env = $inputEnv;
                    break;
                }
            }
        }
    }
    putenv("APP_ENV=$env");
}